/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HampePanel.java
 *
 * Created on 6 avr. 2010, 09:41:38
 */

package musicwriter.guiswing;

import java.awt.event.ActionListener;
import javax.swing.JPanel;
import musicwriter.donnees.Note;

/**
 *
 * @author Ancmin
 */
public class HampePanel extends JPanel {


    private ActionListener actionListener = null;
    private Note.HampeDirection hampeDirection = Note.HampeDirection.AUTOMATIC;

    

    /** Creates new form HampePanel */
    public HampePanel() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButtonUp = new javax.swing.JToggleButton();
        jToggleButtonDown = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(32, 64));
        setMinimumSize(new java.awt.Dimension(32, 64));
        setPreferredSize(new java.awt.Dimension(21, 64));
        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(1);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        buttonGroup1.add(jToggleButtonUp);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(HampePanel.class);
        jToggleButtonUp.setIcon(resourceMap.getIcon("jToggleButtonUp.icon")); // NOI18N
        jToggleButtonUp.setText(resourceMap.getString("jToggleButtonUp.text")); // NOI18N
        jToggleButtonUp.setFocusable(false);
        jToggleButtonUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonUp.setName("jToggleButtonUp"); // NOI18N
        jToggleButtonUp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonUpActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButtonUp);

        buttonGroup1.add(jToggleButtonDown);
        jToggleButtonDown.setIcon(resourceMap.getIcon("jToggleButtonDown.icon")); // NOI18N
        jToggleButtonDown.setText(resourceMap.getString("jToggleButtonDown.text")); // NOI18N
        jToggleButtonDown.setFocusable(false);
        jToggleButtonDown.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonDown.setName("jToggleButtonDown"); // NOI18N
        jToggleButtonDown.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDownActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButtonDown);

        add(jToolBar1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonUpActionPerformed
        hampeDirection = Note.HampeDirection.HAUT;
        actionListener.actionPerformed(evt);
                
    }//GEN-LAST:event_jToggleButtonUpActionPerformed

    private void jToggleButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDownActionPerformed
        hampeDirection = Note.HampeDirection.BAS;
        actionListener.actionPerformed(evt);
    }//GEN-LAST:event_jToggleButtonDownActionPerformed

    


    public void addListener(ActionListener a)
    {
        this.actionListener = a;
    }



    Note.HampeDirection getHampeDirection()
    {
        return hampeDirection;
    }
    
    
    void setHampeDirection(Note.HampeDirection direction)
    {
        jToggleButtonUp.setSelected(false);
        jToggleButtonDown.setSelected(false);
        
        if(direction == Note.HampeDirection.HAUT)
            jToggleButtonUp.setSelected(true);
        else if(direction == Note.HampeDirection.BAS)
            jToggleButtonDown.setSelected(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton jToggleButtonDown;
    private javax.swing.JToggleButton jToggleButtonUp;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
