/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NotesConfigurationPanel.java
 *
 * Created on 28 avr. 2010, 00:27:01
 */

package musicwriter.guiswing;

import musicwriter.controller.Controller;
import musicwriter.donnees.Histoire;
import musicwriter.donnees.Voix;
import musicwriter.donnees.actions.PartitionActionSelectionPasDeVoix;
import musicwriter.donnees.actions.PartitionActionSelectionVoixSet;

/**
 *
 * @author Ancmin
 */
public class NotesConfigurationPanel extends javax.swing.JPanel {


    private final Controller partitionPanel;

    /** Creates new form NotesConfigurationPanel */
    public NotesConfigurationPanel(Controller partitionPanel) {
        initComponents();
        this.partitionPanel = partitionPanel;
    }



    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbarNotes = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel7 = new javax.swing.JLabel();
        selectionAlterationPanel = new musicwriter.guiswing.AlterationPanel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jLabel8 = new javax.swing.JLabel();
        selectionDureePanel = new musicwriter.guiswing.DureePanel();
        cmdSelectionTriolets = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jLabel9 = new javax.swing.JLabel();
        selectionHampePanel = new musicwriter.guiswing.HampePanel();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jLabel10 = new javax.swing.JLabel();
        noteFigurePanel1 = new musicwriter.guiswing.NoteFigurePanel();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        toolbarNotes.setFloatable(false);
        toolbarNotes.setRollover(true);
        toolbarNotes.setName("toolbarNotes"); // NOI18N

        jSeparator4.setName("jSeparator4"); // NOI18N
        toolbarNotes.add(jSeparator4);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(NotesConfigurationPanel.class);
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        toolbarNotes.add(jLabel7);

        selectionAlterationPanel.setName("selectionAlterationPanel"); // NOI18N
        toolbarNotes.add(selectionAlterationPanel);

        jSeparator5.setName("jSeparator5"); // NOI18N
        toolbarNotes.add(jSeparator5);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        toolbarNotes.add(jLabel8);

        selectionDureePanel.setMaximumSize(new java.awt.Dimension(60, 2147483647));
        selectionDureePanel.setName("selectionDureePanel"); // NOI18N
        toolbarNotes.add(selectionDureePanel);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getActionMap(NotesConfigurationPanel.class, this);
        cmdSelectionTriolets.setAction(actionMap.get("actionDureeTrioletsBoiteDeDialogue")); // NOI18N
        cmdSelectionTriolets.setIcon(null);
        cmdSelectionTriolets.setText(resourceMap.getString("cmdSelectionTriolets.text")); // NOI18N
        cmdSelectionTriolets.setFocusable(false);
        cmdSelectionTriolets.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdSelectionTriolets.setName("cmdSelectionTriolets"); // NOI18N
        cmdSelectionTriolets.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarNotes.add(cmdSelectionTriolets);

        jSeparator6.setName("jSeparator6"); // NOI18N
        toolbarNotes.add(jSeparator6);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        toolbarNotes.add(jLabel9);

        selectionHampePanel.setMaximumSize(new java.awt.Dimension(32, 64));
        selectionHampePanel.setName("selectionHampePanel"); // NOI18N
        selectionHampePanel.setPreferredSize(new java.awt.Dimension(16, 64));
        toolbarNotes.add(selectionHampePanel);

        jSeparator7.setName("jSeparator7"); // NOI18N
        toolbarNotes.add(jSeparator7);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        toolbarNotes.add(jLabel10);

        noteFigurePanel1.setName("noteFigurePanel1"); // NOI18N
        toolbarNotes.add(noteFigurePanel1);

        jSeparator8.setName("jSeparator8"); // NOI18N
        toolbarNotes.add(jSeparator8);

        jButton1.setIcon(null);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        toolbarNotes.add(jButton1);

        jButton2.setIcon(null);
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        toolbarNotes.add(jButton2);

        add(toolbarNotes);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getHistoire().executer(new PartitionActionSelectionVoixSet(getPartitionPanel().getSelection(), new Voix()));
        getPartitionPanel().calculerModificationSelection();
        getPartitionPanel().repaint();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getHistoire().executer(new PartitionActionSelectionPasDeVoix(getPartitionPanel().getSelection()));
        getPartitionPanel().calculerModificationSelection();
        getPartitionPanel().repaint();
}//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdSelectionTriolets;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private musicwriter.guiswing.NoteFigurePanel noteFigurePanel1;
    private musicwriter.guiswing.AlterationPanel selectionAlterationPanel;
    private musicwriter.guiswing.DureePanel selectionDureePanel;
    private musicwriter.guiswing.HampePanel selectionHampePanel;
    private javax.swing.JToolBar toolbarNotes;
    // End of variables declaration//GEN-END:variables

    private Controller getPartitionPanel() {
        return partitionPanel;
    }

    private Histoire getHistoire() {
        return partitionPanel.getHistoire();
    }

}
