package musicwriter.guiswing;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelHelpNoteDeplacement.java
 *
 * Created on 14 juil. 2010, 19:41:29
 */

/**
 *
 * @author Ancmin
 */
public class PanelHelpNoteDeplacement extends javax.swing.JPanel {

    /** Creates new form PanelHelpNoteDeplacement */
    public PanelHelpNoteDeplacement() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectionCopierPlus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSelectionCopierPlus3 = new javax.swing.JLabel();
        lblSelectionCopierPlus1 = new javax.swing.JLabel();
        lblSelectionCopierPlus2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(464, 41));
        setMinimumSize(new java.awt.Dimension(464, 41));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(464, 41));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(PanelHelpNoteDeplacement.class);
        lblSelectionCopierPlus.setBackground(resourceMap.getColor("lblSelectionCopierPlus.background")); // NOI18N
        lblSelectionCopierPlus.setIcon(resourceMap.getIcon("lblSelectionCopierPlus.icon")); // NOI18N
        lblSelectionCopierPlus.setText(resourceMap.getString("lblSelectionCopierPlus.text")); // NOI18N
        lblSelectionCopierPlus.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblSelectionCopierPlus.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblSelectionCopierPlus.setName("lblSelectionCopierPlus"); // NOI18N
        lblSelectionCopierPlus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(lblSelectionCopierPlus);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        lblSelectionCopierPlus3.setBackground(resourceMap.getColor("lblSelectionCopierPlus3.background")); // NOI18N
        lblSelectionCopierPlus3.setText(resourceMap.getString("lblSelectionCopierPlus3.text")); // NOI18N
        lblSelectionCopierPlus3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblSelectionCopierPlus3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSelectionCopierPlus3.setName("lblSelectionCopierPlus3"); // NOI18N
        lblSelectionCopierPlus3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblSelectionCopierPlus3);

        lblSelectionCopierPlus1.setBackground(resourceMap.getColor("lblSelectionCopierPlus1.background")); // NOI18N
        lblSelectionCopierPlus1.setText(resourceMap.getString("lblSelectionCopierPlus1.text")); // NOI18N
        lblSelectionCopierPlus1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblSelectionCopierPlus1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSelectionCopierPlus1.setName("lblSelectionCopierPlus1"); // NOI18N
        lblSelectionCopierPlus1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblSelectionCopierPlus1);

        add(jPanel1);

        lblSelectionCopierPlus2.setBackground(resourceMap.getColor("lblSelectionCopierPlus2.background")); // NOI18N
        lblSelectionCopierPlus2.setText(resourceMap.getString("lblSelectionCopierPlus2.text")); // NOI18N
        lblSelectionCopierPlus2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblSelectionCopierPlus2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSelectionCopierPlus2.setName("lblSelectionCopierPlus2"); // NOI18N
        lblSelectionCopierPlus2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(lblSelectionCopierPlus2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSelectionCopierPlus;
    private javax.swing.JLabel lblSelectionCopierPlus1;
    private javax.swing.JLabel lblSelectionCopierPlus2;
    private javax.swing.JLabel lblSelectionCopierPlus3;
    // End of variables declaration//GEN-END:variables

    void setModeJusteDeplacement() {
        lblSelectionCopierPlus.setVisible(true);
        lblSelectionCopierPlus.setOpaque(false);
        lblSelectionCopierPlus.repaint();
    }

    void setModeCopie() {
        lblSelectionCopierPlus.setVisible(true);
        lblSelectionCopierPlus.setOpaque(true);
        lblSelectionCopierPlus.repaint();
    }

}
