/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ToolBarDefinedWithStrings.java
 *
 * Created on 18 mai 2010, 21:13:23
 */

package musicwriter.guiswing;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;

/**
 *
 * @author Ancmin
 */
public class ToolBarDefinedWithStrings extends javax.swing.JPanel {

    private Map<String, JToggleButton> buttonToString = new HashMap<String, JToggleButton>();


    /** Creates new form ToolBarDefinedWithStrings */
    public ToolBarDefinedWithStrings(ArrayList<String> listeBoutons ) {
        initComponents();


        for(String s : listeBoutons)
        {
            ImageIcon img = ImageLoaderSwing.getImageIconPourBoutonNullSiRien(s + ".png");
            if(img != null)
            {
                JToggleButton b = new JToggleButton();
                b.setIcon(img);
                b.setFocusable(false);
                b.setToolTipText(s);
                jToolBar.add(b);
                buttonToString.put(s, b);
            }
            
        }
 
    }


    public ArrayList<String> getStringSelected() {
        ArrayList<String> S = new ArrayList<String>();
        
        for(String nom : buttonToString.keySet())
        {
            if(buttonToString.get(nom).isSelected())
                S.add(nom);
        }

        return S;
    }



    public void setStringSelected(ArrayList<String> strings) {

        for(JToggleButton b : buttonToString.values())
        {
            b.setSelected(false);
        }


        for(String nom : strings)
        {
            if(buttonToString.containsKey(nom))
                buttonToString.get(nom).setSelected(true);
        }
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jToolBar.setFloatable(false);
        jToolBar.setName("jToolBar"); // NOI18N
        add(jToolBar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables

}
