/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateDialog.java
 *
 * Created on 25 févr. 2012, 13:49:42
 */
package musicwriter.guiswing;

import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import org.jdom.Element;
import org.jdom.Document;
import org.jdom.JDOMException;
import org.jdom.input.SAXBuilder;

/**
 *
 * @author Ancmin
 */
public class UpdateDialog extends javax.swing.JDialog {
//Chemin vers le fichier XML 







    /** Creates new form UpdateDialog
     * @param parent
     * @param modal  
     */
    public UpdateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        UpdateDesktopVersion.Update update = UpdateDesktopVersion.getUpdate();
        
        if(update == null)
        {
            noUpdatePanel.setVisible(true);
            ThereisAnUpdatePanel.setVisible(false);
        }
        else
        {
            noUpdatePanel.setVisible(false);
            ThereisAnUpdatePanel.setVisible(true);
            
            lblUrl.setText(update.getUrl());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noUpdatePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ThereisAnUpdatePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUrl = new JUrlLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        noUpdatePanel.setName("noUpdatePanel"); // NOI18N

        jLabel3.setText("You are using the latest version of Open Musicwriter.");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout noUpdatePanelLayout = new javax.swing.GroupLayout(noUpdatePanel);
        noUpdatePanel.setLayout(noUpdatePanelLayout);
        noUpdatePanelLayout.setHorizontalGroup(
            noUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noUpdatePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        noUpdatePanelLayout.setVerticalGroup(
            noUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noUpdatePanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel3)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(noUpdatePanel);

        ThereisAnUpdatePanel.setName("ThereisAnUpdatePanel"); // NOI18N

        jLabel1.setText("There is an update version:");
        jLabel1.setName("jLabel1"); // NOI18N

        lblUrl.setText("zererserser");
        lblUrl.setName("lblUrl"); // NOI18N

        javax.swing.GroupLayout ThereisAnUpdatePanelLayout = new javax.swing.GroupLayout(ThereisAnUpdatePanel);
        ThereisAnUpdatePanel.setLayout(ThereisAnUpdatePanelLayout);
        ThereisAnUpdatePanelLayout.setHorizontalGroup(
            ThereisAnUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThereisAnUpdatePanelLayout.createSequentialGroup()
                .addGroup(ThereisAnUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThereisAnUpdatePanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addGroup(ThereisAnUpdatePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        ThereisAnUpdatePanelLayout.setVerticalGroup(
            ThereisAnUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThereisAnUpdatePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(lblUrl)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        getContentPane().add(ThereisAnUpdatePanel);

        jButton1.setText("OK");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                UpdateDialog dialog = new UpdateDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ThereisAnUpdatePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JPanel noUpdatePanel;
    // End of variables declaration//GEN-END:variables
}
