/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DivisionsExceptionnellesDialog.java
 *
 * Created on 7 mars 2010, 16:37:43
 */

package musicwriter.guiswing.dialogs;

import javax.swing.ImageIcon;
import musicwriter.donnees.Duree;
import musicwriter.donnees.Rational;
import musicwriter.guiswing.ImageLoaderSwing;

/**
 *
 * @author Ancmin
 */
public class DivisionsExceptionnellesDialog extends javax.swing.JDialog {
    private boolean annule;

    /** Creates new form DivisionsExceptionnellesDialog */
    public DivisionsExceptionnellesDialog(java.awt.Frame parent, boolean modal, int nombre) {
        super(parent, modal);
        initComponents();
        jSpinnerNumero.setValue(new Integer(nombre));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dureeBasePanel = new musicwriter.guiswing.DureePanel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerNumero = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        cmdOK = new javax.swing.JButton();
        cmdAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(DivisionsExceptionnellesDialog.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);

        dureeBasePanel.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        dureeBasePanel.setName("dureeBasePanel"); // NOI18N
        dureeBasePanel.setPreferredSize(new java.awt.Dimension(209, 50));
        jPanel1.add(dureeBasePanel);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);

        jSpinnerNumero.setFont(resourceMap.getFont("jSpinnerNumero.font")); // NOI18N
        jSpinnerNumero.setMaximumSize(new java.awt.Dimension(32767, 36));
        jSpinnerNumero.setName("jSpinnerNumero"); // NOI18N
        jSpinnerNumero.setPreferredSize(new java.awt.Dimension(64, 36));
        jPanel1.add(jSpinnerNumero);

        getContentPane().add(jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        cmdOK.setIcon(resourceMap.getIcon("cmdOK.icon")); // NOI18N
        cmdOK.setText(resourceMap.getString("cmdOK.text")); // NOI18N
        cmdOK.setName("cmdOK"); // NOI18N
        cmdOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOKActionPerformed(evt);
            }
        });
        jPanel2.add(cmdOK);

        cmdAnnuler.setIcon(resourceMap.getIcon("cmdAnnuler.icon")); // NOI18N
        cmdAnnuler.setText(resourceMap.getString("cmdAnnuler.text")); // NOI18N
        cmdAnnuler.setName("cmdAnnuler"); // NOI18N
        cmdAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAnnulerActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAnnuler);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOKActionPerformed
        setVisible(false);
        annule = false;
}//GEN-LAST:event_cmdOKActionPerformed

    public boolean isAnnule() {
        return annule;
    }





    public Duree getDuree()
    {
        int numero = (Integer) jSpinnerNumero.getValue();

        return new Duree(dureeBasePanel.getDuree().getRational().multiplier(new Rational(1, numero)));
    }

    private void cmdAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAnnulerActionPerformed
        setVisible(false);
        annule = true;
}//GEN-LAST:event_cmdAnnulerActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DivisionsExceptionnellesDialog dialog = new DivisionsExceptionnellesDialog(new javax.swing.JFrame(), true,3);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAnnuler;
    private javax.swing.JButton cmdOK;
    private musicwriter.guiswing.DureePanel dureeBasePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerNumero;
    // End of variables declaration//GEN-END:variables



    /**
     *
     * @param numero
     * @return la partie entière du logarithme en base 2 de numero
     *
     * exemple :
     * log2(2) = 1
     * log2(3) = 1
     * log2(4) = 2
     * log2(5) = 2 ...
     * log2(8) = 3
     *
     */
    private long log2(long numero) {
        return (long) (Math.log(numero) / Math.log10(2));
    }
}
