/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InstrumentsDialog.java
 * Cette boîte de dialogue permet de choisir un instrument.
 * Created on 18 janv. 2010, 20:01:13
 */

package musicwriter.guiswing.dialogs;

import musicwriter.donnees.Instrument;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ancmin
 */
public class InstrumentsDialog extends javax.swing.JDialog {

    DefaultListModel instruments = new DefaultListModel();



    private void instrumentAdd(Instrument instrument)
    {
        instruments.add(instruments.size(), instrument);
    }


    
    private Instrument instrument;
    /** Creates new form InstrumentsDialog */
    public InstrumentsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        instrumentAdd(new Instrument(0));
        instrumentAdd( new Instrument(6));
        instrumentAdd( new Instrument(8));
        instrumentAdd( new Instrument(9));
        instrumentAdd( new Instrument(10));
        instrumentAdd( new Instrument(11));
        instrumentAdd( new Instrument(12));
        instrumentAdd( new Instrument(13));
        instrumentAdd( new Instrument(14));
        instrumentAdd( new Instrument(15));
        instrumentAdd( new Instrument(16));

        instrumentAdd( new Instrument(21));
        instrumentAdd( new Instrument(22));
        instrumentAdd( new Instrument(23));

        instrumentAdd( new Instrument(24));
        
        instrumentAdd( new Instrument(40));
        instrumentAdd( new Instrument(41));
        instrumentAdd( new Instrument(42));
        instrumentAdd(new Instrument(43));


        instrumentAdd( new Instrument(46));
        instrumentAdd( new Instrument(47));

        instrumentAdd( new Instrument(56));
        instrumentAdd( new Instrument(57));
        instrumentAdd( new Instrument(58));
        instrumentAdd( new Instrument(59));
        instrumentAdd( new Instrument(60));

        instrumentAdd( new Instrument(64));
        instrumentAdd( new Instrument(65));
        instrumentAdd( new Instrument(66));
        instrumentAdd( new Instrument(67));
        instrumentAdd( new Instrument(68));
        instrumentAdd( new Instrument(69));
        instrumentAdd( new Instrument(70));
        
        instrumentAdd( new Instrument(71));
        instrumentAdd( new Instrument(72));
        instrumentAdd( new Instrument(73));
        instrumentAdd( new Instrument(74));
        instrumentAdd( new Instrument(75));
        jListInstruments.setCellRenderer(new InstrumentCellRenderer());
        jListInstruments.setModel(instruments);
        
        
        setGlassPane(new GhostGlassPane());
        
    }

    public Instrument getInstrument()
    {
        return instrument;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jListInstruments = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(InstrumentsDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(400, 600));
        setName("Form"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jListInstruments.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListInstruments.setDragEnabled(true);
        jListInstruments.setName("jListInstruments"); // NOI18N
        jListInstruments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListInstrumentsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListInstruments);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListInstrumentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListInstrumentsMouseClicked
            if(jListInstruments.getSelectedIndex() >= 0)
                instrument = (Instrument) instruments.get(jListInstruments.getSelectedIndex());
            else
                instrument = null;
            setVisible(false);
    }//GEN-LAST:event_jListInstrumentsMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InstrumentsDialog dialog = new InstrumentsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListInstruments;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
