/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MesureSignatureChangementDialog.java
 *
 * Created on 15 janv. 2010, 17:23:36
 */

package musicwriter.guiswing.dialogs;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import musicwriter.donnees.MesureSignature;

/**
 *
 * @author Ancmin
 */
public class MesureSignatureChangementDialog extends javax.swing.JDialog {

    private MesureSignature signature;

    public MesureSignature getSignature() {
        return signature;
    }

    /** Creates new form MesureSignatureChangementDialog */
    public MesureSignatureChangementDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ((CardLayout) panContainer.getLayout()).show(panContainer, "normal");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtNumerateur1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumerateur2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumerateur3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumerateur4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDenominateur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cmdOK = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(MesureSignatureChangementDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        panContainer.setName("panContainer"); // NOI18N
        panContainer.setLayout(new java.awt.CardLayout());

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        txtNumerateur1.setFont(resourceMap.getFont("txtNumerateur4.font")); // NOI18N
        txtNumerateur1.setText(resourceMap.getString("txtNumerateur1.text")); // NOI18N
        txtNumerateur1.setMaximumSize(new java.awt.Dimension(64, 28));
        txtNumerateur1.setMinimumSize(new java.awt.Dimension(32, 20));
        txtNumerateur1.setName("txtNumerateur1"); // NOI18N
        txtNumerateur1.setPreferredSize(new java.awt.Dimension(32, 20));
        jPanel3.add(txtNumerateur1);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel3.add(jLabel1);

        txtNumerateur2.setFont(resourceMap.getFont("txtNumerateur4.font")); // NOI18N
        txtNumerateur2.setText(resourceMap.getString("txtNumerateur2.text")); // NOI18N
        txtNumerateur2.setMaximumSize(new java.awt.Dimension(64, 28));
        txtNumerateur2.setMinimumSize(new java.awt.Dimension(32, 20));
        txtNumerateur2.setName("txtNumerateur2"); // NOI18N
        txtNumerateur2.setPreferredSize(new java.awt.Dimension(32, 20));
        jPanel3.add(txtNumerateur2);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel3.add(jLabel3);

        txtNumerateur3.setFont(resourceMap.getFont("txtNumerateur4.font")); // NOI18N
        txtNumerateur3.setText(resourceMap.getString("txtNumerateur3.text")); // NOI18N
        txtNumerateur3.setMaximumSize(new java.awt.Dimension(64, 28));
        txtNumerateur3.setMinimumSize(new java.awt.Dimension(32, 20));
        txtNumerateur3.setName("txtNumerateur3"); // NOI18N
        txtNumerateur3.setPreferredSize(new java.awt.Dimension(32, 20));
        jPanel3.add(txtNumerateur3);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel3.add(jLabel2);

        txtNumerateur4.setFont(resourceMap.getFont("txtNumerateur4.font")); // NOI18N
        txtNumerateur4.setText(resourceMap.getString("txtNumerateur4.text")); // NOI18N
        txtNumerateur4.setMaximumSize(new java.awt.Dimension(64, 28));
        txtNumerateur4.setMinimumSize(null);
        txtNumerateur4.setName("txtNumerateur4"); // NOI18N
        txtNumerateur4.setPreferredSize(null);
        jPanel3.add(txtNumerateur4);

        jPanel2.add(jPanel3);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel2.add(jLabel4);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel2.add(jLabel5);

        txtDenominateur.setFont(resourceMap.getFont("txtNumerateur4.font")); // NOI18N
        txtDenominateur.setText(resourceMap.getString("txtDenominateur.text")); // NOI18N
        txtDenominateur.setMaximumSize(new java.awt.Dimension(64, 28));
        txtDenominateur.setName("txtDenominateur"); // NOI18N
        jPanel2.add(txtDenominateur);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel2.add(jLabel6);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        cmdOK.setIcon(resourceMap.getIcon("cmdOK.icon")); // NOI18N
        cmdOK.setText(resourceMap.getString("cmdOK.text")); // NOI18N
        cmdOK.setName("cmdOK"); // NOI18N
        cmdOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOKActionPerformed(evt);
            }
        });
        jPanel4.add(cmdOK);

        cmdCancel.setIcon(resourceMap.getIcon("cmdCancel.icon")); // NOI18N
        cmdCancel.setText(resourceMap.getString("cmdCancel.text")); // NOI18N
        cmdCancel.setName("cmdCancel"); // NOI18N
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCancel);

        jPanel2.add(jPanel4);

        panContainer.add(jPanel2, "personalise");

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton2.setFont(resourceMap.getFont("jButton9.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jButton2, gridBagConstraints);

        jButton3.setFont(resourceMap.getFont("jButton9.font")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jButton3, gridBagConstraints);

        jButton4.setFont(resourceMap.getFont("jButton9.font")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jButton4, gridBagConstraints);

        jButton5.setFont(resourceMap.getFont("jButton9.font")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jButton5, gridBagConstraints);

        jButton6.setFont(resourceMap.getFont("jButton9.font")); // NOI18N
        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jButton6, gridBagConstraints);

        jButton7.setFont(resourceMap.getFont("jButton9.font")); // NOI18N
        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jButton7, gridBagConstraints);

        jButton8.setFont(resourceMap.getFont("jButton9.font")); // NOI18N
        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jButton8, gridBagConstraints);

        jButton9.setFont(resourceMap.getFont("jButton9.font")); // NOI18N
        jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jButton9, gridBagConstraints);

        jButton10.setFont(resourceMap.getFont("jButton10.font")); // NOI18N
        jButton10.setText(resourceMap.getString("jButton10.text")); // NOI18N
        jButton10.setName("jButton10"); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        jPanel1.add(jButton10, gridBagConstraints);

        panContainer.add(jPanel1, "normal");

        getContentPane().add(panContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void retourner(MesureSignature signature)
    {
        this.signature = signature;
        setVisible(false);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        retourner(new MesureSignature(2, 2));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        retourner(new MesureSignature(3, 2));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        retourner(new MesureSignature(2, 4));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        retourner(new MesureSignature(3, 4));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        retourner(new MesureSignature(4, 4));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        retourner(new MesureSignature(6, 8));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        retourner(new MesureSignature(5, 4));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        retourner(new MesureSignature(6, 4));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        ((CardLayout) panContainer.getLayout()).show(panContainer, "personalise");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void cmdOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOKActionPerformed
        retourner(new MesureSignature(Long.parseLong(txtNumerateur1.getText()),
                                    Long.parseLong(txtNumerateur2.getText()),
                                    Long.parseLong(txtNumerateur3.getText()),
                                    Long.parseLong(txtNumerateur4.getText()),
                                    Long.parseLong(txtDenominateur.getText())));

    }//GEN-LAST:event_cmdOKActionPerformed

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        signature = null;
        setVisible(false);
    }//GEN-LAST:event_cmdCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MesureSignatureChangementDialog dialog = new MesureSignatureChangementDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdOK;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panContainer;
    private javax.swing.JTextField txtDenominateur;
    private javax.swing.JTextField txtNumerateur1;
    private javax.swing.JTextField txtNumerateur2;
    private javax.swing.JTextField txtNumerateur3;
    private javax.swing.JTextField txtNumerateur4;
    // End of variables declaration//GEN-END:variables

}
