/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NoteDecorationPanel.java
 *
 * Created on 17 mai 2010, 19:01:16
 */

package musicwriter.guiswing.dialogs;

import java.util.ArrayList;
import musicwriter.donnees.Note;

/**
 *
 * @author Ancmin
 */
public class NoteDecorationPanel extends javax.swing.JDialog {
    private boolean ok = false;

    /** Creates new form NoteDecorationPanel */
    public NoteDecorationPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelOrnements1 = new musicwriter.guiswing.PanelNoteOrnements();
        jLabel2 = new javax.swing.JLabel();
        panelNoteArticulations1 = new musicwriter.guiswing.PanelNoteArticulations();
        jLabel3 = new javax.swing.JLabel();
        noteFigurePanel = new musicwriter.guiswing.NoteFigurePanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(NoteDecorationPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);

        panelOrnements1.setName("panelOrnements1"); // NOI18N
        getContentPane().add(panelOrnements1);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);

        panelNoteArticulations1.setName("panelNoteArticulations1"); // NOI18N
        getContentPane().add(panelNoteArticulations1);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);

        noteFigurePanel.setName("noteFigurePanel"); // NOI18N
        getContentPane().add(noteFigurePanel);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ok = true;
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ok = false;
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NoteDecorationPanel dialog = new NoteDecorationPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private musicwriter.guiswing.NoteFigurePanel noteFigurePanel;
    private musicwriter.guiswing.PanelNoteArticulations panelNoteArticulations1;
    private musicwriter.guiswing.PanelNoteOrnements panelOrnements1;
    // End of variables declaration//GEN-END:variables


    public ArrayList<String> getArticulations()
    {
        return panelNoteArticulations1.getStringSelected();
    }

    public ArrayList<String> getOrnements()
    {
        return panelOrnements1.getStringSelected();
    }


    public Note.NoteFigure getNoteFigure()
    {
        return noteFigurePanel.getNoteFigure();
    }

    public boolean isOK() {
        return ok;
    }

    public void setArticulations(ArrayList<String> articulations) {
        panelNoteArticulations1.setStringSelected(articulations);
    }


    public void setOrnements(ArrayList<String> ornements) {
        panelOrnements1.setStringSelected(ornements);
    }
}
