/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TonalitePanel.java
 *
 * Created on 26 janv. 2011, 14:30:59
 */

package musicwriter.guiswing.dialogs;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JToggleButton;
import musicwriter.donnees.Tonalite;
import musicwriter.guiswing.ImageLoaderSwing;

/**
 *
 * @author Ancmin
 */
public class TonalitePanel extends javax.swing.JPanel {
    private Tonalite tonalite;
    private ActionListener action;



    /** Creates new form TonalitePanel */
    public TonalitePanel() {
        initComponents();

        int width = 48;
        mnuTonalite0.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonalite0.svg", width));
        mnuTonaliteD1.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonalited1.svg", width));
        mnuTonaliteD2.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonalited2.svg", width));
        mnuTonaliteD3.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonalited3.svg", width));
        mnuTonaliteD4.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonalited4.svg", width));
        mnuTonaliteD5.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonalited5.svg", width));
        mnuTonaliteD6.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonalited6.svg", width));
        mnuTonaliteD7.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonalited7.svg", width));

        mnuTonaliteB1.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonaliteb1.svg", width));
        mnuTonaliteB2.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonaliteb2.svg", width));
        mnuTonaliteB3.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonaliteb3.svg", width));
        mnuTonaliteB4.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonaliteb4.svg", width));
        mnuTonaliteB5.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonaliteb5.svg", width));
        mnuTonaliteB6.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonaliteb6.svg", width));
        mnuTonaliteB7.setIcon(ImageLoaderSwing.getSVGImageIconAvecWidth("tonaliteb7.svg", width));

        for(Component m : getComponents())
        {
            if(m instanceof JToggleButton)
            {
                ((JToggleButton) m).addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        valider((JToggleButton) e.getSource());
                    }
                });

                m.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                    @Override
                    public void mouseMoved(java.awt.event.MouseEvent evt) {
                        JToggleButton bouton = (JToggleButton) evt.getSource();
                        lblTonaliteNom.setText(Tonalite.getNomTonalite(JToggleButtonToInt(bouton)));
                    }
                });
                
                m.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        if(getTonalite() != null)
                            lblTonaliteNom.setText(getTonalite().getNomTonalite());
                    }
                });
            }
        }
        

    }

    public void setAction(ActionListener action) {
        this.action = action;
    }


    private JToggleButton tonaliteToButton(Tonalite tonalite)
    {
        switch(tonalite.getDiesesNombre())
        {
            case -7: return mnuTonaliteB7;
            case -6: return mnuTonaliteB6;
            case -5: return mnuTonaliteB5;
            case -4: return mnuTonaliteB4;
            case -3: return mnuTonaliteB3;
            case -2: return mnuTonaliteB2;
            case -1: return mnuTonaliteB1;
            case 0: return mnuTonalite0;
            case 7: return mnuTonaliteD7;
            case 6: return mnuTonaliteD6;
            case 5: return mnuTonaliteD5;
            case 4: return mnuTonaliteD4;
            case 3: return mnuTonaliteD3;
            case 2: return mnuTonaliteD2;
            case 1: return mnuTonaliteD1;
            default: return null;
        }
    }



public void setTonalite(Tonalite tonalite)
{
    tonaliteToButton(tonalite).setSelected(true);
    this.tonalite = tonalite;
}

    public Tonalite getTonalite() {
        return tonalite;
    }




    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        mnuTonaliteD4 = new javax.swing.JToggleButton();
        mnuTonaliteB5 = new javax.swing.JToggleButton();
        mnuTonaliteD1 = new javax.swing.JToggleButton();
        mnuTonalite0 = new javax.swing.JToggleButton();
        mnuTonaliteD5 = new javax.swing.JToggleButton();
        lblTonaliteNom = new javax.swing.JLabel();
        mnuTonaliteB4 = new javax.swing.JToggleButton();
        mnuTonaliteD7 = new javax.swing.JToggleButton();
        mnuTonaliteB3 = new javax.swing.JToggleButton();
        mnuTonaliteD2 = new javax.swing.JToggleButton();
        mnuTonaliteB2 = new javax.swing.JToggleButton();
        mnuTonaliteB1 = new javax.swing.JToggleButton();
        mnuTonaliteD6 = new javax.swing.JToggleButton();
        mnuTonaliteD3 = new javax.swing.JToggleButton();
        mnuTonaliteB7 = new javax.swing.JToggleButton();
        mnuTonaliteB6 = new javax.swing.JToggleButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(mnuTonaliteD4);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(TonalitePanel.class);
        mnuTonaliteD4.setForeground(resourceMap.getColor("mnuTonaliteD4.foreground")); // NOI18N
        mnuTonaliteD4.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD4.setName("mnuTonaliteD4"); // NOI18N
        mnuTonaliteD4.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteD4mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(mnuTonaliteD4, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteB5);
        mnuTonaliteB5.setForeground(resourceMap.getColor("mnuTonaliteB5.foreground")); // NOI18N
        mnuTonaliteB5.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB5.setName("mnuTonaliteB5"); // NOI18N
        mnuTonaliteB5.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mnuTonaliteB5JToggleButton3MouseMoved(evt);
            }
        });
        mnuTonaliteB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteB5mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        add(mnuTonaliteB5, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteD1);
        mnuTonaliteD1.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD1.setName("mnuTonaliteD1"); // NOI18N
        mnuTonaliteD1.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteD1mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(mnuTonaliteD1, gridBagConstraints);

        buttonGroup1.add(mnuTonalite0);
        mnuTonalite0.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonalite0.setName("mnuTonalite0"); // NOI18N
        mnuTonalite0.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonalite0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonalite0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        add(mnuTonalite0, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteD5);
        mnuTonaliteD5.setForeground(resourceMap.getColor("mnuTonaliteD5.foreground")); // NOI18N
        mnuTonaliteD5.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD5.setName("mnuTonaliteD5"); // NOI18N
        mnuTonaliteD5.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteD5mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(mnuTonaliteD5, gridBagConstraints);

        lblTonaliteNom.setFont(resourceMap.getFont("lblTonaliteNom.font")); // NOI18N
        lblTonaliteNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTonaliteNom.setText(resourceMap.getString("lblTonaliteNom.text")); // NOI18N
        lblTonaliteNom.setName("lblTonaliteNom"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        add(lblTonaliteNom, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteB4);
        mnuTonaliteB4.setForeground(resourceMap.getColor("mnuTonaliteB4.foreground")); // NOI18N
        mnuTonaliteB4.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB4.setName("mnuTonaliteB4"); // NOI18N
        mnuTonaliteB4.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mnuTonaliteB4JToggleButton3MouseMoved(evt);
            }
        });
        mnuTonaliteB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteB4mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(mnuTonaliteB4, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteD7);
        mnuTonaliteD7.setForeground(resourceMap.getColor("mnuTonaliteD7.foreground")); // NOI18N
        mnuTonaliteD7.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD7.setName("mnuTonaliteD7"); // NOI18N
        mnuTonaliteD7.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mnuTonaliteD7JToggleButton3MouseMoved(evt);
            }
        });
        mnuTonaliteD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteD7mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(mnuTonaliteD7, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteB3);
        mnuTonaliteB3.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB3.setName("mnuTonaliteB3"); // NOI18N
        mnuTonaliteB3.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mnuTonaliteB3JToggleButton3MouseMoved(evt);
            }
        });
        mnuTonaliteB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteB3mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(mnuTonaliteB3, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteD2);
        mnuTonaliteD2.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD2.setName("mnuTonaliteD2"); // NOI18N
        mnuTonaliteD2.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteD2mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 0, 0);
        add(mnuTonaliteD2, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteB2);
        mnuTonaliteB2.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB2.setName("mnuTonaliteB2"); // NOI18N
        mnuTonaliteB2.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mnuTonaliteB2JToggleButton3MouseMoved(evt);
            }
        });
        mnuTonaliteB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteB2mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(mnuTonaliteB2, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteB1);
        mnuTonaliteB1.setFont(resourceMap.getFont("mnuTonaliteB1.font")); // NOI18N
        mnuTonaliteB1.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB1.setName("mnuTonaliteB1"); // NOI18N
        mnuTonaliteB1.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mnuTonaliteB1MouseMoved(evt);
            }
        });
        mnuTonaliteB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 0, 0, 0);
        add(mnuTonaliteB1, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteD6);
        mnuTonaliteD6.setForeground(resourceMap.getColor("mnuTonaliteD6.foreground")); // NOI18N
        mnuTonaliteD6.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD6.setName("mnuTonaliteD6"); // NOI18N
        mnuTonaliteD6.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteD6mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        add(mnuTonaliteD6, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteD3);
        mnuTonaliteD3.setForeground(resourceMap.getColor("mnuTonaliteD3.foreground")); // NOI18N
        mnuTonaliteD3.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD3.setName("mnuTonaliteD3"); // NOI18N
        mnuTonaliteD3.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteD3mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 0, 0);
        add(mnuTonaliteD3, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteB7);
        mnuTonaliteB7.setForeground(resourceMap.getColor("mnuTonaliteB7.foreground")); // NOI18N
        mnuTonaliteB7.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB7.setName("mnuTonaliteB7"); // NOI18N
        mnuTonaliteB7.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteB7mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(mnuTonaliteB7, gridBagConstraints);

        buttonGroup1.add(mnuTonaliteB6);
        mnuTonaliteB6.setForeground(resourceMap.getColor("mnuTonaliteB6.foreground")); // NOI18N
        mnuTonaliteB6.setMaximumSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB6.setName("mnuTonaliteB6"); // NOI18N
        mnuTonaliteB6.setPreferredSize(new java.awt.Dimension(24, 9));
        mnuTonaliteB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTonaliteB6mnuTonaliteB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        add(mnuTonaliteB6, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuTonaliteD4mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteD4mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteD4mnuTonaliteB1ActionPerformed

    private void mnuTonaliteB5mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteB5mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteB5mnuTonaliteB1ActionPerformed

    private void mnuTonaliteD1mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteD1mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteD1mnuTonaliteB1ActionPerformed

    private void mnuTonalite0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonalite0ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonalite0ActionPerformed

    private void mnuTonaliteD5mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteD5mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteD5mnuTonaliteB1ActionPerformed

    private void mnuTonaliteB4mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteB4mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteB4mnuTonaliteB1ActionPerformed

    private void mnuTonaliteD7mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteD7mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteD7mnuTonaliteB1ActionPerformed

    private void mnuTonaliteB3mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteB3mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteB3mnuTonaliteB1ActionPerformed

    private void mnuTonaliteD2mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteD2mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteD2mnuTonaliteB1ActionPerformed

    private void mnuTonaliteB2mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteB2mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteB2mnuTonaliteB1ActionPerformed

    private void mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteB1ActionPerformed

    private void mnuTonaliteD6mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteD6mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteD6mnuTonaliteB1ActionPerformed

    private void mnuTonaliteD3mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteD3mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteD3mnuTonaliteB1ActionPerformed

    private void mnuTonaliteB7mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteB7mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteB7mnuTonaliteB1ActionPerformed

    private void mnuTonaliteB6mnuTonaliteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTonaliteB6mnuTonaliteB1ActionPerformed
        // TODO add your handling code here:
        valider((JToggleButton) evt.getSource());
}//GEN-LAST:event_mnuTonaliteB6mnuTonaliteB1ActionPerformed

    private void mnuTonaliteB1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTonaliteB1MouseMoved
        JToggleButton bouton = (JToggleButton) evt.getSource();
        lblTonaliteNom.setText(Tonalite.getNomTonalite(JToggleButtonToInt(bouton)));
}//GEN-LAST:event_mnuTonaliteB1MouseMoved

    private void mnuTonaliteB2JToggleButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTonaliteB2JToggleButton3MouseMoved
        // TODO add your handling code here:
        JToggleButton bouton = (JToggleButton) evt.getSource();
        lblTonaliteNom.setText(Tonalite.getNomTonalite(JToggleButtonToInt(bouton)));
}//GEN-LAST:event_mnuTonaliteB2JToggleButton3MouseMoved

    private void mnuTonaliteB3JToggleButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTonaliteB3JToggleButton3MouseMoved
        // TODO add your handling code here:
        JToggleButton bouton = (JToggleButton) evt.getSource();
        lblTonaliteNom.setText(Tonalite.getNomTonalite(JToggleButtonToInt(bouton)));
}//GEN-LAST:event_mnuTonaliteB3JToggleButton3MouseMoved

    private void mnuTonaliteB4JToggleButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTonaliteB4JToggleButton3MouseMoved
        // TODO add your handling code here:
        JToggleButton bouton = (JToggleButton) evt.getSource();
        lblTonaliteNom.setText(Tonalite.getNomTonalite(JToggleButtonToInt(bouton)));
}//GEN-LAST:event_mnuTonaliteB4JToggleButton3MouseMoved

    private void mnuTonaliteB5JToggleButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTonaliteB5JToggleButton3MouseMoved
        // TODO add your handling code here:
        JToggleButton bouton = (JToggleButton) evt.getSource();
        lblTonaliteNom.setText(Tonalite.getNomTonalite(JToggleButtonToInt(bouton)));
}//GEN-LAST:event_mnuTonaliteB5JToggleButton3MouseMoved

    private void mnuTonaliteD7JToggleButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTonaliteD7JToggleButton3MouseMoved
        // TODO add your handling code here:
        JToggleButton bouton = (JToggleButton) evt.getSource();
        lblTonaliteNom.setText(Tonalite.getNomTonalite(JToggleButtonToInt(bouton)));
}//GEN-LAST:event_mnuTonaliteD7JToggleButton3MouseMoved



    static private int JToggleButtonToInt(JToggleButton bouton)
    {
        if(bouton.getName().equals("mnuTonalite0"))
            return 0;
        else if (bouton.getName().startsWith("mnuTonaliteD"))
              return  Integer.parseInt(bouton.getName().substring(bouton.getName().length()-1));
        else
              return   -Integer.parseInt(bouton.getName().substring(bouton.getName().length()-1));

    }

    private void valider(JToggleButton bouton) {
        tonalite = new Tonalite(JToggleButtonToInt(bouton));

        if(action != null)
            action.actionPerformed(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblTonaliteNom;
    private javax.swing.JToggleButton mnuTonalite0;
    private javax.swing.JToggleButton mnuTonaliteB1;
    private javax.swing.JToggleButton mnuTonaliteB2;
    private javax.swing.JToggleButton mnuTonaliteB3;
    private javax.swing.JToggleButton mnuTonaliteB4;
    private javax.swing.JToggleButton mnuTonaliteB5;
    private javax.swing.JToggleButton mnuTonaliteB6;
    private javax.swing.JToggleButton mnuTonaliteB7;
    private javax.swing.JToggleButton mnuTonaliteD1;
    private javax.swing.JToggleButton mnuTonaliteD2;
    private javax.swing.JToggleButton mnuTonaliteD3;
    private javax.swing.JToggleButton mnuTonaliteD4;
    private javax.swing.JToggleButton mnuTonaliteD5;
    private javax.swing.JToggleButton mnuTonaliteD6;
    private javax.swing.JToggleButton mnuTonaliteD7;
    // End of variables declaration//GEN-END:variables

}
