/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TransposerDialog.java
 *
 * Created on 26 janv. 2011, 14:56:09
 */

package musicwriter.guiswing.dialogs;

import musicwriter.donnees.Intervalle;
import musicwriter.donnees.Tonalite;

/**
 *
 * @author Ancmin
 */
public class TransposerDialog extends javax.swing.JDialog {
    private boolean ok;

    /** Creates new form TransposerDialog */
    public TransposerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tonalitePanel1.setTonalite(new Tonalite(0));
        tonalitePanel2.setTonalite(tonalitePanel1.getTonalite());
    }

    public boolean isOk() {
        return ok;
    }


    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tonalitePanel1 = new musicwriter.guiswing.dialogs.TonalitePanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tonalitePanel2 = new musicwriter.guiswing.dialogs.TonalitePanel();
        jPanel3 = new javax.swing.JPanel();
        cmdOK = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(TransposerDialog.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel2.add(jLabel1);

        tonalitePanel1.setMinimumSize(null);
        tonalitePanel1.setName("tonalitePanel1"); // NOI18N
        jPanel2.add(tonalitePanel1);

        getContentPane().add(jPanel2);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);

        tonalitePanel2.setMinimumSize(null);
        tonalitePanel2.setName("tonalitePanel2"); // NOI18N
        jPanel1.add(tonalitePanel2);

        getContentPane().add(jPanel1);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        cmdOK.setIcon(resourceMap.getIcon("cmdOK.icon")); // NOI18N
        cmdOK.setText(resourceMap.getString("cmdOK.text")); // NOI18N
        cmdOK.setName("cmdOK"); // NOI18N
        cmdOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOKActionPerformed(evt);
            }
        });
        jPanel3.add(cmdOK);

        cmdCancel.setIcon(resourceMap.getIcon("cmdCancel.icon")); // NOI18N
        cmdCancel.setText(resourceMap.getString("cmdCancel.text")); // NOI18N
        cmdCancel.setName("cmdCancel"); // NOI18N
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCancel);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOKActionPerformed
        ok = true;
        setVisible(false);
    }//GEN-LAST:event_cmdOKActionPerformed

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        ok = false;
        setVisible(false);
    }//GEN-LAST:event_cmdCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TransposerDialog dialog = new TransposerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    public Intervalle getIntervalle()
    {
        return new Intervalle(tonalitePanel1.getTonalite().getToniqueMajeure(),
                              tonalitePanel2.getTonalite().getToniqueMajeure());
    }



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private musicwriter.guiswing.dialogs.TonalitePanel tonalitePanel1;
    private musicwriter.guiswing.dialogs.TonalitePanel tonalitePanel2;
    // End of variables declaration//GEN-END:variables

}
