/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaletteOngletPanel.java
 *
 * Created on 7 avr. 2010, 12:50:29
 */

package musicwriter.guiswing.palette;

import java.awt.Component;

/**
 *
 * @author Ancmin
 */
public class PaletteOngletPanel extends javax.swing.JPanel {


    /** Creates new form PaletteOngletPanel */
    public PaletteOngletPanel(String nom) {
        initComponents();
        jToggleButton.setText(nom);
    }

    PaletteOngletPanel(String nom, Component composant) {
        this(nom);
        jScrollPane.setViewportView(composant);
  //      jScrollPane.setPreferredSize(composant.getPreferredSize());
    //    jScrollPane.setMinimumSize(composant.getMinimumSize());
    jScrollPane.setVisible(true);
    
        setExpanded(false);
        composant.doLayout();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panEntete = new javax.swing.JPanel();
        panSeparation = new javax.swing.JPanel();
        toolBarName = new javax.swing.JToolBar();
        jToggleButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(PaletteOngletPanel.class);
        jLabel1.setBackground(resourceMap.getColor("jLabel1.background")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(2000, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 16));
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(0, 16));

        jLabel2.setBackground(resourceMap.getColor("jLabel1.background")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(2000, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(0, 16));
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(0, 16));

        setName("Form"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        panEntete.setName("panEntete"); // NOI18N
        panEntete.setLayout(new javax.swing.BoxLayout(panEntete, javax.swing.BoxLayout.PAGE_AXIS));

        panSeparation.setBackground(resourceMap.getColor("panSeparation.background")); // NOI18N
        panSeparation.setMaximumSize(new java.awt.Dimension(32767, 2));
        panSeparation.setMinimumSize(new java.awt.Dimension(10, 2));
        panSeparation.setName("panSeparation"); // NOI18N
        panSeparation.setPreferredSize(new java.awt.Dimension(100, 2));
        panEntete.add(panSeparation);

        toolBarName.setFloatable(false);
        toolBarName.setRollover(true);
        toolBarName.setName("toolBarName"); // NOI18N

        jToggleButton.setIcon(resourceMap.getIcon("jToggleButton.icon")); // NOI18N
        jToggleButton.setText(resourceMap.getString("jToggleButton.text")); // NOI18N
        jToggleButton.setFocusable(false);
        jToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jToggleButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButton.setMaximumSize(new java.awt.Dimension(32767, 21));
        jToggleButton.setName("jToggleButton"); // NOI18N
        jToggleButton.setSelectedIcon(resourceMap.getIcon("jToggleButton.selectedIcon")); // NOI18N
        jToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonActionPerformed(evt);
            }
        });
        toolBarName.add(jToggleButton);

        panEntete.add(toolBarName);

        add(panEntete);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        add(jLabel3);

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setMinimumSize(new java.awt.Dimension(23, 53));
        jScrollPane.setName("jScrollPane"); // NOI18N
        add(jScrollPane);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonActionPerformed
        setExpanded(getExpanded());
    }//GEN-LAST:event_jToggleButtonActionPerformed



    private boolean getExpanded()
    {
        return jToggleButton.isSelected();
    }

    void setExpanded(boolean expanded)
    {
        this.jToggleButton.setSelected(expanded);
        
//        for(Component c : this.getComponents())
//        {
//            if(c != panEntete)
//                 c.setVisible(expanded);
//        }

        jLabel3.setVisible(expanded);
        jScrollPane.setVisible(expanded);
        
        if(expanded)
   //         si on étend un PaletteOngletPanel, on va ranger les autres
        {
            for(Component c : this.getParent().getComponents())
            {
                if(c != this)
                if(c instanceof PaletteOngletPanel)
                    ((PaletteOngletPanel) c).setExpanded(false);
            }
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JToggleButton jToggleButton;
    private javax.swing.JPanel panEntete;
    private javax.swing.JPanel panSeparation;
    private javax.swing.JToolBar toolBarName;
    // End of variables declaration//GEN-END:variables

}
